import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
import { site } from "@/lib/site";

export const metadata = { title: "Plan Your Visit", description: "Plan your Sunday at The Pentecostals of Manhattan. Sundays at 10:30 AM in Manhattan, Kansas." };

export default function VisitPage(){return <main>
<PageHero eyebrow="Plan your Sunday" title="You can walk in as you are." copy="New places can feel uncertain. Here is everything you need to know before your first Sunday at POM." image="/images/welcome-team.jpg" />
<section className="section"><div className="shell grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">The basics</p></div><div className="grid border-t border-black/15 md:grid-cols-3">{[["When","Sunday","10:30 AM"],["Where","530 Richards Dr.","Manhattan, KS"],["How long","About","90 minutes"]].map(([a,b,c])=><div key={a} className="border-b border-black/15 py-7 md:border-r md:px-7 first:pl-0 last:border-r-0"><p className="eyebrow">{a}</p><p className="mt-8 text-3xl font-black uppercase tracking-[-.04em]">{b}<br/><span className="text-[#ff4f32]">{c}</span></p></div>)}</div></div></section>
<section className="section !pt-0"><div className="shell grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><Reveal><div className="relative min-h-[650px]"><Image src="/images/worship.jpg" alt="Worship at POM" fill className="object-cover" sizes="(max-width:1024px)100vw,65vw"/></div></Reveal><div className="grid gap-4"><Reveal><div className="relative aspect-[4/3]"><Image src="/images/kids-face.jpg" alt="A child at POM" fill className="object-cover"/></div></Reveal><Reveal delay={.08}><div className="bg-[#101010] p-8 text-white"><p className="eyebrow !text-white/40">What to expect</p><div className="mt-10 space-y-7">{["Friendly people","Casual dress","Vibrant worship","Practical Bible preaching","A safe place for kids"].map((x,i)=><div key={x} className="flex gap-5 border-t border-white/15 pt-4"><span className="text-[#ff4f32] text-xs">0{i+1}</span><p className="font-bold uppercase tracking-[-.02em]">{x}</p></div>)}</div></div></Reveal></div></div></section>
<section id="plan" className="section bg-[#e9e2d7]"><div className="shell grid gap-12 lg:grid-cols-2 lg:items-center"><Reveal><div><p className="eyebrow mb-6">Getting here</p><h2 className="big-heading">530 Richards Dr.</h2><p className="copy mt-7 max-w-xl">We are in Manhattan, Kansas. Come a few minutes early, meet someone at the door, and make yourself at home.</p><div className="mt-8 flex flex-wrap gap-3"><a href={site.maps} target="_blank" rel="noreferrer" className="button button-accent">Get directions ↗</a><Link href="/contact" className="button">Tell us you’re coming ↗</Link></div></div></Reveal><Reveal delay={.08}><div className="relative aspect-[4/3] overflow-hidden"><Image src="/images/directions.png" alt="Directions to POM" fill className="object-cover"/></div></Reveal></div></section>
</main>}
